# -- PostgreSQL ClusterIP Service ----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "rce-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "rce-platform.name" . }}
    app.kubernetes.io/component: postgres
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
      name: tcp-postgresql
